mlrun:
  api:
    image:
      tag: 1.7.0-rc22
  ui:
    images:
      tag: 1.7.0-rc22
    sidecars:
      logCollector:
        image:
          tag: 1.7.0-rc22
  db:
    image:
      tag: 8.0

nuclio:
  controller:
    image:
      tag: 1.13.3-amd64
  dashboard:
    image:
      tag: 1.13.3-amd64
